language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - jruby-head

bundler_args: --without deploy

script: bundle exec rake test:ruby

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

services:
  - mongodb

branches:
  only:
    - master
    - release

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
